### PR TITLE
Refactor Window Manager interaction

### PR DESCRIPTION
**Pull request by gfgit**
This is a replacement for #2029 rebased on latest master

Main differences with initial idea:
- Now `ILXQtTaskbarAbstractBackend` is stored globally inside `LXQtPanelApplication` (infact I should drop "taskbar" part of the name)
- LXQtPanel uses this class for auto-hide logic (not sure if it's working yet)

TODO: port other plugins which currently directly use X11 to use this abstract interface

### CODE REVIEW

File: plugin-desktopswitch/desktopswitch.cpp [hunk 1]
```diff
@@ -293,11 +254,11 @@ void DesktopSwitch::settingsChanged()
...
         if (panel()->isHorizontal())
         {
-            mDesktops->setDesktopLayout(NET::OrientationHorizontal, columns, mRows, mWidget.isRightToLeft() ? NET::DesktopLayoutCornerTopRight : NET::DesktopLayoutCornerTopLeft);
+            //mDesktops->setDesktopLayout(NET::OrientationHorizontal, columns, mRows, mWidget.isRightToLeft() ? NET::DesktopLayoutCornerTopRight : NET::DesktopLayoutCornerTopLeft);
         }
         else
         {
-            mDesktops->setDesktopLayout(NET::OrientationHorizontal, mRows, columns, mWidget.isRightToLeft() ? NET::DesktopLayoutCornerTopRight : NET::DesktopLayoutCornerTopLeft);
+            //mDesktops->setDesktopLayout(NET::OrientationHorizontal, mRows, columns, mWidget.isRightToLeft() ? NET::DesktopLayoutCornerTopRight : NET::DesktopLayoutCornerTopLeft);
         }
```
Comment (tsujan) [inline plugin-desktopswitch/desktopswitch.cpp:262]: Why is `NETRootInfo::setDesktopLayout()` removed under X11? Isn't this a regression with X11?

File: plugin-desktopswitch/desktopswitch.cpp [hunk 2]
```diff
@@ -185,56 +179,23 @@ void DesktopSwitch::refresh()
...
-
-    QFlags<NET::WindowTypeMask> normalFlag;
-    normalFlag |= NET::NormalMask;
-    normalFlag |= NET::DialogMask;
-    normalFlag |= NET::UtilityMask;
-
-    return !NET::typeMatchesMask(info.windowType(NET::AllTypesMask), normalFlag);
+    // Backend should emit signals only for higlightable windows and ignore others
+    // TODO: check
+    return true;
```
Comment (tsujan) [inline plugin-desktopswitch/desktopswitch.cpp:186]: This means a regression under X11; doesn't it?

File: plugin-desktopswitch/desktopswitch.cpp (hunk 1 above)
Comment (gfgit) [reply plugin-desktopswitch/desktopswitch.cpp:262]: Hi, I didn't understand what that code is about. However it should go to backend now.

File: plugin-desktopswitch/desktopswitch.cpp (hunk 2 above)
Comment (gfgit) [reply plugin-desktopswitch/desktopswitch.cpp:186]: It should not change behavior. Backend just ignores non-highlightable windows so there is not need to filter them again.
See [LXQtTaskbarX11Backend::acceptWindow()](https://github.com/lxqt/lxqt-panel/blob/8b78adda8784fe52e3d5a4154cf71aef71f018ab/panel/backends/xcb/lxqttaskbarbackend_x11.cpp#L117)

Comment (gfgit) [reply plugin-desktopswitch/desktopswitch.cpp:186]: We could entirely remove the functiom

File: plugin-desktopswitch/desktopswitch.cpp (hunk 1 above)
Comment (tsujan) [reply plugin-desktopswitch/desktopswitch.cpp:262]: > it should go to backend now.

Yes, and it should be done here, in this PR.

File: plugin-desktopswitch/desktopswitch.cpp (hunk 2 above)
Comment (tsujan) [reply plugin-desktopswitch/desktopswitch.cpp:186]: You'll decide what to to do here. A part of code reviewing is to make sure that this PR won't cause any problem in the *current* functionality. All I'm saying is that the PR seems to cause a regression in this case, under X11.

Comment (tsujan) [reply plugin-desktopswitch/desktopswitch.cpp:186]: Oh, very sorry! It was GitHub's fault: it didn't load a file; so, I couldn't search in it. I saw that function after downloading the branch (which I should have done from the start).

Please remove the redundant function(s).

File: plugin-desktopswitch/desktopswitch.cpp (hunk 1 above)
Comment (tsujan) [reply plugin-desktopswitch/desktopswitch.cpp:262]: Sorry for my mistake! The PR is big, and GitHub didn't load a file. I cloned your branch now, to read it without GitHub's hassles.

Comment (tsujan) [reply plugin-desktopswitch/desktopswitch.cpp:262]: > I didn't understand what that code is abou

See https://api.kde.org/frameworks/kwindowsystem/html/classNETRootInfo.html#a06f991c0b1540e779e5e324404337241

If I'm not mistaken again, this is really removed in your PR: the desktop layout isn't set according to the pager anymore.

File: plugin-taskbar/lxqttaskgroup.cpp [hunk 3]
```diff
@@ -631,66 +632,48 @@ bool LXQtTaskGroup::onWindowChanged(WId window, NET::Properties prop, NET::Prope
...
-            // Force refresh urgency
-            //TODO: maybe do it in common place with NET::WM2Urgency
-            std::for_each(buttons.begin(), buttons.end(), std::bind(&LXQtTaskButton::setUrgencyHint, std::placeholders::_1, urgency || info.hasState(NET::DemandsAttention)));
+            if (!set_urgency)
+                urgency = mBackend->applicationDemandsAttention(window);
+            std::for_each(buttons.begin(), buttons.end(), std::bind(&LXQtTaskButton::setUrgencyHint, std::placeholders::_1, urgency));
             set_urgency = false;
 
-            if (info.hasState(NET::SkipTaskbar))
-                onWindowRemoved(window);
```
Comment (tsujan) [inline plugin-taskbar/lxqttaskgroup.cpp:692]: Any idea why the above two lines were included in the first place?

Comment (gfgit) [reply plugin-taskbar/lxqttaskgroup.cpp:692]: Well windows could change the "skip taskbar" property at any time, so the taskbar should remove/re-add them based on the value.
This logic was moved to backend, although it was only removing exiting non-acceptable window like this code does while it was missing the "re-add" part.
Fixed in last commit

**Comment by tsujan** [comment]
When compiling your latest branch:

```
/usr/bin/ld: CMakeFiles/lxqt-panel.dir/lxqt-panel_autogen/mocs_compilation.cpp.o:(.data.rel.ro._ZTV23LXQtTaskBarDummyBackend[_ZTV23LXQtTaskBarDummyBackend]+0x130): undefined reference to `LXQtTaskBarDummyBackend::setDesktopLayout(Qt::Orientation, int, int, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [panel/CMakeFiles/lxqt-panel.dir/build.make:681: panel/lxqt-panel] Error 1
make[1]: *** [CMakeFiles/Makefile2:2509: panel/CMakeFiles/lxqt-panel.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

File: panel/backends/lxqttaskbardummybackend.cpp [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+{
+    //No-op
+}
+
+bool LXQtTaskBarDummyBackend::isWindowOnScreen(QScreen *, WId) const
+{
+    return false;
+}
+
+bool setDesktopLayout(Qt::Orientation, int, int, bool)
```
[the remark this answers is not in the document]
Comment (gfgit) [reply panel/backends/lxqttaskbardummybackend.cpp]: Fixed

**Comment by tsujan** [comment]
Sadly, setting of the desktop layout doesn't work with KWin 6.0.4 anymore. That may not be related to this PR because it doesn't work with lxqt-panel 2.0.1 either, although I'm sure that the Qt5-based version of KWin followed lxqt-panel's Switcher when "Number of rows" were changed in the latter (ignore KDE System Settings).

This needs to be tested with another WM.

File: panel/lxqtpanel.cpp [hunk 5]
```diff
@@ -1407,48 +1416,60 @@ Plugin* LXQtPanel::findPlugin(const ILXQtPanelPlugin* iPlugin) const
...
         break;
 
     case ILXQtPanel::PositionBottom:
-        y = mGeometry.top() - windowSize.height();
+        y = 0 - windowSize.height();
         break;
 
     case ILXQtPanel::PositionLeft:
-        x = mGeometry.right();
+        x = geometry().right();
```
Comment (tsujan) [inline panel/lxqtpanel.cpp:1433]: Since you've used local coordinates, this should be `x = geometry().width();` — although there may be no difference in practice because we don't put a panel between two screens.

**Review by tsujan — CHANGES_REQUESTED** [review]

File: panel/lxqtpanel.cpp [hunk 6]
```diff
@@ -1407,48 +1416,60 @@ Plugin* LXQtPanel::findPlugin(const ILXQtPanelPlugin* iPlugin) const
...
         break;
 
     case ILXQtPanel::PositionRight:
-        x = mGeometry.left() - windowSize.width();
+        x = geometry().left() - windowSize.width();
```
Comment (tsujan) [inline panel/lxqtpanel.cpp:1437]: Ditto, but this one is incorrect. It should be `x = 0 - windowSize.width();` (please also add that `0` to emphasize the locality of coordinates).

File: panel/lxqtpanel.cpp [hunk 7]
```diff
@@ -1407,48 +1416,60 @@ Plugin* LXQtPanel::findPlugin(const ILXQtPanelPlugin* iPlugin) const
...
 
-    if (res.bottom() > panelScreen.bottom())
-        res.moveBottom(panelScreen.bottom());
+        if (res.right() > panelScreen.right())
+            res.moveRight(panelScreen.right());
 
-    if (res.left() < panelScreen.left())
-        res.moveLeft(panelScreen.left());
+        if (res.bottom() > panelScreen.bottom())
+            res.moveBottom(panelScreen.bottom() - mGeometry.top());
```
Comment (tsujan) [inline panel/lxqtpanel.cpp:1465]: These checks are for preventing off-screen popups with any alignment. `mGeometry` has no role in them. Please remove it and make them as they were.

File: panel/lxqtpanel.cpp [hunk 8]
```diff
@@ -1407,48 +1416,60 @@ Plugin* LXQtPanel::findPlugin(const ILXQtPanelPlugin* iPlugin) const
...
 
-    if (res.top() < panelScreen.top())
-        res.moveTop(panelScreen.top());
+        if (res.left() < panelScreen.left())
+            res.moveLeft(panelScreen.left());
+
+        if (res.top() < panelScreen.top())
+            res.moveTop(panelScreen.top() - mGeometry.top());
```
Comment (tsujan) [inline panel/lxqtpanel.cpp:1471]: Ditto.

File: panel/lxqtpanel.cpp [hunk 9]
```diff
@@ -1407,48 +1416,60 @@ Plugin* LXQtPanel::findPlugin(const ILXQtPanelPlugin* iPlugin) const
...
-    if (mActualScreenNum < screens.size())
-        panelScreen = screens.at(mActualScreenNum)->geometry();
-    // NOTE: We cannot use AvailableGeometry() which returns the work area here because when in a
-    // multihead setup with different resolutions. In this case, the size of the work area is limited
-    // by the smallest monitor and may be much smaller than the current screen and we will place the
-    // menu at the wrong place. This is very bad for UX. So let's use the full size of the screen.
-    if (res.right() > panelScreen.right())
-        res.moveRight(panelScreen.right());
+    // Map to global coordinates
+    res = QRect(mapToGlobal(res.topLeft()), mapToGlobal(res.bottomRight()));
```
Comment (tsujan) [inline panel/lxqtpanel.cpp:1444]: Supposing that the mentioned issues are fixed, this converting of global to local and then returning to the first coordinates seem redundant, whether under X11 or under Wayland. The only meaningful change that has happened is using of `geometry()` instead of `mGeometry`.

**Comment by stefonarch** [comment]
There is  basic issue with this PR and the ones based upon. If no lxqt-panel is installed and `ilxqtpanel.h  ilxqtpanelplugin.h  lxqtpanelglobals.h  pluginsettings.h` aren't already available in `/usr/include/lxqt` build fails:
```
[  2%] Built target sysstat_autogen

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/plugin-taskbar/lxqttaskbarplugin.h"
into
  "SRC:/build/plugin-taskbar/taskbar_autogen/EWIEGA46WW/moc_lxqttaskbarplugin.cpp"
Process failed with return value 1

Command
-------
/usr/lib/qt6/moc "-DLXQT_DATA_DIR=\"/usr/share\"" "-DLXQT_ETC_XDG_DIR=\"/etc/xdg\"" "-DLXQT_GRAPHICS_DIR=\"/usr/share/lxqt/graphics\"" "-DLXQT_MAJOR_VERSION=\"2\"" "-DLXQT_MINOR_VERSION=\"0\"" "-DLXQT_PANEL_VERSION=\"2.0.0\"" "-DLXQT_PATCH_VERSION=\"0\"" "-DLXQT_RELATIVE_SHARE_DIR=\"lxqt\"" "-DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\"" "-DLXQT_SHARE_DIR=\"/usr/share/lxqt\"" "-DLXQT_SHARE_TRANSLATIONS_DIR=\"/usr/share/lxqt/translations\"" "-DLXQT_VERSION=\"2.0.0\"" "-DPLUGIN_DIR=\"/usr/lib/lxqt-panel\"" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_FOREACH -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_DESKTOPSWITCH_PLUGIN -DWITH_FANCYMENU_PLUGIN -DWITH_MAINMENU_PLUGIN -DWITH_QUICKLAUNCH_PLUGIN -DWITH_SHOWDESKTOP_PLUGIN -DWITH_TASKBAR_PLUGIN -I/home/stef/git/lxqt/lxqt-panel/build/plugin-taskbar -I/home/stef/git/lxqt/lxqt-panel/plugin-taskbar -I/usr/include/qt6/QtWidgets -I/usr/include/qt6 -I/usr/include/qt6/QtCore -I/usr/lib/qt6/mkspecs/linux-g++ -I/usr/include/qt6/QtGui -I/usr/include/lxqt -I/usr/include/lxqt/LXQt -I/usr/include/KF6/KWindowSystem -I/usr/include/qt6/QtDBus -I/usr/include/qt6xdg -I/usr/include/qt6/QtXml -I/usr/include/qt6xdgiconloader -I/usr/include/qt6xdgiconloader/4.0.0 -I/usr/include/qt6/QtSvg -I/usr/include/lxqt-globalkeys -I/usr/include -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed --include /home/stef/git/lxqt/lxqt-panel/build/plugin-taskbar/taskbar_autogen/moc_predefs.h --output-dep-file -o /home/stef/git/lxqt/lxqt-panel/build/plugin-taskbar/taskbar_autogen/EWIEGA46WW/moc_lxqttaskbarplugin.cpp /home/stef/git/lxqt/lxqt-panel/plugin-taskbar/lxqttaskbarplugin.h

Output
------
/home/stef/git/lxqt/lxqt-panel/plugin-taskbar/lxqttaskbarplugin.h:62:1: error: Undefined interface
```
People without an  existing installation of lxqt-panel got `/home/stef/git/lxqt/lxqt-panel/plugin-taskbar/lxqttaskbarplugin.h:62:1: error: Undefined interface` at 72%.

**Comment by tsujan** [comment]
Confirming @stefonarch's surprising observation.

**Comment by stefonarch** [comment]
@gfgit Do you have some time to look at the remaining issues?

**Comment by gfgit** [comment]
Hi, I'm back. Compile issues should be fixed by latest commit

**Comment by gfgit** [comment]
@tsujan I've reverted commit regarding panel positioning. It only affects Wayland which is not yet merged.
To be honest `lxqtpanel.cpp` is a bit messy, with multiple "delayed" calls and workarounds for various issues which include also `desktopswitch.cpp` warning about `realign()`.
Since this must change anyway for Wayland because we cannot rely on global coordinates there, it might be better to clean the logic a bit.

**Comment by stefonarch** [comment]
>Compile issues should be fixed by latest commit

Confirmed. I see that now there are 6 files instead of the previous 4:

```
stef@archlinux:lxqt-panel$ cd /usr/include/lxqt
stef@archlinux:lxqt$ ls
ilxqtpanel.h        LXQt                pluginsettings.h
ilxqtpanelplugin.h  lxqtpanelglobals.h
stef@archlinux:lxqt$ sudo mv *.h /tmp
stef@archlinux:lxqt$ ls
LXQt
stef@archlinux:lxqt$ ls
ilxqtpanel.h                   lxqtpanelglobals.h
ilxqtpanelplugin.h             lxqttaskbartypes.h
ilxqttaskbarabstractbackend.h  pluginsettings.h
LXQt

```
Will do some test later on X11.

**Comment by tsujan** [comment]
> Since this must change anyway for Wayland because we cannot rely on global coordinates there

Under Wayland, Qt's global coordinates are actually local and calculated relative to the window.

Please resolve the conflicts with the master branch.

**Comment by gfgit** [comment]
@tsujan Conflicts are fixed now

**Comment by tsujan** [comment]
> Conflicts are fixed now

Thanks! I'll continue reviewing tomorrow.

**Comment by stefonarch** [comment]
@gfgit I get compiling errors now:

```
[ 28%] Building CXX object plugin-fancymenu/CMakeFiles/fancymenu.dir/lxqtfancymenu.cpp.o                                              
/tmp/makepkg/lxqt-panel-git/src/lxqt-panel/plugin-desktopswitch/desktopswitch.cpp: In constructor 'DesktopSwitch::DesktopSwitch(const ILXQtPanelPluginStartupInfo&)':
/tmp/makepkg/lxqt-panel-git/src/lxqt-panel/plugin-desktopswitch/desktopswitch.cpp:55:5: error: class 'DesktopSwitch' does not have any field named 'mDesktops'
   55 |     mDesktops(nullptr),
```

**Comment by gfgit** [comment]
Hi, it may be a left over from the merge conflict. Does it build fine if you remove the line?

Il 6 giugno 2024 13:38:09 CEST, Standreas ***@***.***> ha scritto:

**Comment by stefonarch** [comment]
>Does it build fine if you remove the line?

Yes, thanks.

File: plugin-desktopswitch/desktopswitchconfiguration.cpp [hunk 10]
```diff
@@ -64,18 +65,25 @@ void DesktopSwitchConfiguration::loadSettings()
...
-        QTimer *timer = new QTimer(this);
-        timer->setInterval(400);
-        timer->setSingleShot(true);
-        connect(timer, &QTimer::timeout,       this, [=] { KX11Extras::setDesktopName(i, edit->text()); });
-        connect(edit,  &QLineEdit::textEdited, this, [=] { timer->start(); });
+        //QTimer *timer = new QTimer(this);
+        //timer->setInterval(400);
+        //timer->setSingleShot(true);
+        //connect(timer, &QTimer::timeout,       this, [=] { KX11Extras::setDesktopName(i, edit->text()); });
+        //connect(edit,  &QLineEdit::textEdited, this, [=] { timer->start(); });
```
Comment (tsujan) [inline plugin-desktopswitch/desktopswitchconfiguration.cpp:86]: Would you please explain why you removed this under X11 instead of limiting it to X11? Or is it added to another place which I can't find?

**Review by tsujan — APPROVED** [review]
I can't say that my review is complete — it's done in separate stages, and the code has been changed after each of them — but, as far as my free time allowed, I found some problems that are fixed now. IMO, this PR has waited enough, considering that 2 other works depend on it.

So, GTM.

File: plugin-desktopswitch/desktopswitchconfiguration.cpp (hunk 10 above)
Comment (gfgit) [reply plugin-desktopswitch/desktopswitchconfiguration.cpp]: Hi, this was a quick fix because there will be no Wayland equivalent of setting desktop name.
At first I though about removing it from X11 too to keep both at same level but it's good to keep it.

**Comment by gfgit** [comment]
Thanks!

**Comment by tsujan** [comment]
> Thanks!

Thank _you_ for doing this great job!

Please also rebase your other PR if it needs that. I hope we could merge it and @marcusbritanicus's PR soon because we need more testers.

**Comment by marcusbritanicus** [comment]
I am having a rather strange compilation issue: I have not seen anyone else complain about it, so it might be a problem in my setup. But it would be nice to figure out the issue.

```
FAILED: panel/lxqt-panel                                                                                                                                                                                                                                                   
: && /usr/bin/c++ -fno-exceptions -Wall -Wextra -Wchar-subscripts -Wno-long-long -Wpointer-arith -Wundef -Wformat-security -Wnon-virtual-dtor -Woverloaded-virtual -Wpedantic -fdiagnostics-color=always -O3 -DNDEBUG -Wl,-Bsymbolic-functions    -Wl,--export-dynamic -rdynamic panel/CMakeFiles/lxqt-panel.dir/lxqt-panel_autogen/mocs_compilation.cpp.o panel/CMakeFiles/lxqt-panel.dir/main.cpp.o panel/CMakeFiles/lxqt-panel.dir/panelpluginsmodel.cpp.o panel/CMakeFiles/lxqt-panel.dir/windownotifier.cpp.o panel/CMakeFiles/lxqt-panel.dir/lxqtpanel.cpp.o panel/CMakeFiles/lxqt-panel.dir/lxqtpanelapplication.cpp.o panel/CMakeFiles/lxqt-panel.dir/lxqtpanellayout.cpp.o panel/CMakeFiles/lxqt-panel.dir/plugin.cpp.o panel/CMakeFiles/lxqt-panel.dir/pluginsettings.cpp.o panel/CMakeFiles/lxqt-panel.dir/popupmenu.cpp.o panel/CMakeFiles/lxqt-panel.dir/pluginmoveprocessor.cpp.o panel/CMakeFiles/lxqt-panel.dir/lxqtpanelpluginconfigdialog.cpp.o panel/CMakeFiles/lxqt-panel.dir/config/configpaneldialog.cpp.o panel/CMakeFiles/lxqt-panel.dir/config/configplacement.cpp.o panel/CMakeFiles/lxqt-panel.dir/config/configstyling.cpp.o panel/CMakeFiles/lxqt-panel.dir/config/configpluginswidget.cpp.o panel/CMakeFiles/lxqt-panel.dir/config/addplugindialog.cpp.o panel/CMakeFiles/lxqt-panel.dir/backends/ilxqttaskbarabstractbackend.cpp.o panel/CMakeFiles/lxqt-panel.dir/backends/lxqttaskbardummybackend.cpp.o panel/CMakeFiles/lxqt-panel.dir/backends/xcb/lxqttaskbarbackend_x11.cpp.o panel/CMakeFiles/lxqt-panel.dir/LXQtAppTranslationLoader.cpp.o -o panel/lxqt-panel  /usr/lib/libLayerShellQtInterface.so.6.0.5  plugin-desktopswitch/libdesktopswitch.a  plugin-fancymenu/libfancymenu.a  plugin-mainmenu/libmainmenu.a  plugin-quicklaunch/libquicklaunch.a  plugin-showdesktop/libshowdesktop.a  plugin-taskbar/libtaskbar.a  plugin-statusnotifier/libstatusnotifier.a  plugin-tray/libtray.a  plugin-worldclock/libworldclock.a  plugin-spacer/libspacer.a  /usr/lib/liblxqt-globalkeys-ui.so.2.0.0  /usr/lib/liblxqt-globalkeys.so.2.0.0  /usr/lib/libdbusmenu-lxqt.so.0.1.0  /usr/lib/libQt6Concurrent.so.6.7.1  /usr/lib/libxcb.so  /usr/lib/libxcb-render.so  /usr/lib/libxcb-shape.so  /usr/lib/libxcb-xfixes.so  /usr/lib/libxcb-shm.so  /usr/lib/libxcb-composite.so  /usr/lib/libxcb-damage.so  /usr/lib/libxcb-image.so  /usr/lib/libxcb-randr.so  /usr/lib/libxcb-util.so  -L/usr/lib  -lXtst  /usr/lib/liblxqt.so.2.0.0  /usr/lib/libQt6Xdg.so.4.0.0  /usr/lib/libQt6Xml.so.6.7.1  /usr/lib/libQt6DBus.so.6.7.1  /usr/lib/libQt6XdgIconLoader.so.4.0.0  /usr/lib/libQt6Svg.so.6.7.1  /usr/lib/libglib-2.0.so  /usr/lib/libgobject-2.0.so  /usr/lib/libgio-2.0.so  /usr/lib/libQt6Widgets.so.6.7.1  /usr/lib/libKF6WindowSystem.so.5.249.0  /usr/lib/libQt6Gui.so.6.7.1  /usr/lib/libQt6Core.so.6.7.1  /usr/lib/libGLX.so  /usr/lib/libOpenGL.so  /usr/lib/libX11.so && :                                                                                                                               
/usr/bin/ld: panel/CMakeFiles/lxqt-panel.dir/backends/xcb/lxqttaskbarbackend_x11.cpp.o: in function `LXQtTaskbarX11Backend::moveApplication(unsigned long long)':                                                                                                          
lxqttaskbarbackend_x11.cpp:(.text+0x229b): undefined reference to `NETRootInfo::moveResizeRequest(unsigned int, int, int, NET::Direction, unsigned char, NET::RequestSource)'
/usr/bin/ld: panel/CMakeFiles/lxqt-panel.dir/backends/xcb/lxqttaskbarbackend_x11.cpp.o: in function `LXQtTaskbarX11Backend::resizeApplication(unsigned long long)':
lxqttaskbarbackend_x11.cpp:(.text+0x23dd): undefined reference to `NETRootInfo::moveResizeRequest(unsigned int, int, int, NET::Direction, unsigned char, NET::RequestSource)'
collect2: error: ld returned 1 exit status
ninja: build stopped: cannot make progress due to previous errors.
```
